Vagrant.configure("2") do |config|
    config.vm.define "ddzubaS" do |server|
      server.vm.box = "ubuntu/bionic64"
      server.vm.hostname = "ddzubaS"
      server.vm.network "private_network", ip: "192.168.56.110"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
      end
      server.vm.provision "shell", path: "scripts/ddzubaS.sh"
      # Add shared folder for logs or token
      server.vm.synced_folder ".", "/vagrant"
    end
  end