Vagrant.configure("2") do |config|
  config.vm.define "ddzubaS" do |server|
    server.vm.box = "ubuntu/bionic64"
    server.vm.hostname = "ddzubaS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    server.vm.provision "shell", path: "scripts/ddzubaS.sh"
    # Add shared folder for logs or token
    server.vm.synced_folder ".", "/vagrant"
  end

  config.vm.define "ddzubaSW" do |worker|
    worker.vm.box = "ubuntu/bionic64"
    worker.vm.hostname = "ddzubaSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    worker.vm.provision "shell", path: "scripts/ddzubaSW.sh"
    # Add shared folder for logs or token
    worker.vm.synced_folder ".", "/vagrant"
  end
end
